
main: Plan_presentation_monday.pdf Summary_presentation_plan.pdf

Plan_presentation_monday.pdf: Plan_presentation_monday.tex
	pdflatex $<

Summary_presentation_plan.pdf: Summary_presentation_plan.tex
	pdflatex $<

clean:
	rm *.pdf *.log *.aux

